### ISSUE TITLE
huobi rest api

### ISSUE THREAD

**Issue by CheremisinVlad** [XinYang-Pan/crypto4j#1]
Hello. First of all thanks your for great work!
I use your huobi  library for my project and it worked well. But now I encounter with this problem
     

>  Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/InvalidDefinitionException
> 	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:74)
> 	at org.springframework.web.client.RestTemplate.<init>(RestTemplate.java:179)
> 	at io.github.xinyangpan.crypto4j.core.util.Crypto4jUtils.restTemplate(Crypto4jUtils.java:22)
> 	at io.github.xinyangpan.crypto4j.core.rest.BaseRestService.<init>(BaseRestService.java:20)
> 	at io.github.xinyangpan.crypto4j.huobi.rest.BaseHuobiRestService.<init>(BaseHuobiRestService.java:38)
> 	at io.github.xinyangpan.crypto4j.huobi.rest.HuobiRestService.<init>(HuobiRestService.java:40)
> 	at Exchanges.saveHuobiData(Exchanges.java:380)
> 	at Main.main(Main.java:22)

I've used tikers() method.
Pls can your fix this issue?

**Comment by CheremisinVlad** [comment]
Thanks for your answer. When i run example above i recieve this error:

> java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/InvalidDefinitionException
> 	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:74)
> 	at org.springframework.web.client.RestTemplate.<init>(RestTemplate.java:179)
> 	at io.github.xinyangpan.crypto4j.core.util.Crypto4jUtils.restTemplate(Crypto4jUtils.java:22)
> 	at io.github.xinyangpan.crypto4j.core.rest.BaseRestService.<init>(BaseRestService.java:20)
> 	at io.github.xinyangpan.crypto4j.huobi.rest.BaseHuobiRestService.<init>(BaseHuobiRestService.java:38)
> 	at io.github.xinyangpan.crypto4j.huobi.rest.HuobiRestService.<init>(HuobiRestService.java:40)
> 	at HuobiRestExample.<clinit>(HuobiRestExample.java:22)
> Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 7 more
> Exception in thread "main" 

I run example without secret and key properties. But it's public market data and it doesn't require of credentials.

This is code i've run:
```
public class HuobiRestExample {

    private static final HuobiRestService huobiRestService;

    private static final String BTCUSDT = "btcusdt";

    static {
        RestProperties restProperties = new RestProperties();
        restProperties.setRestBaseUrl("https://api.huobi.pro");
        
        //
        huobiRestService = new HuobiRestService(restProperties);
    }

    static void tryPartialFill() throws InterruptedException {
        Order order = new Order();
        order.setAccountId(4275858L);
        order.setAmount(new BigDecimal("0.01"));
        order.setPrice(new BigDecimal("7800"));
        order.setSymbol(BTCUSDT);
        order.setType(OrderType.BUY_IOC);
        while (true) {
            Depth depth = huobiRestService.depth(BTCUSDT).fethData();
            HuobiDepthEntry entry = depth.getAsks().get(0);
            //			BigDecimal amount = entry.getPrice().multiply(entry.getQuantity());
            if (order.getAmount().compareTo(entry.getQuantity()) < 0) {
                System.out.println("continue ...  " + entry);
                //				Thread.sleep(1000L);
                //				continue;
            }
            //			System.out.println(entry);
            //			order.setPrice(entry.getPrice().stripTrailingZeros());
            OrderDetail orderDetail = huobiRestService.placeAndQueryDetails(order);
            System.out.println(orderDetail);
            System.out.println(orderDetail.getOrderResult().getState());
            break;
        }
    }

    static void placeOrder() throws InterruptedException {
        Order order = new Order();
        order.setAccountId(4275858L);
        order.setAmount(new BigDecimal("0.1"));
        order.setAmount(new BigDecimal("700"));
        //		order.setPrice(new BigDecimal("7800"));
        order.setSymbol(BTCUSDT);
        order.setType(OrderType.BUY_MARKET);
        OrderDetail orderDetail = huobiRestService.placeAndQueryDetails(order);
        System.out.println(orderDetail);
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(huobiRestService.tickers());
    }

}
```
If any thought what i do wrong?

**Comment by XinYang-Pan** [comment]
![image](https://user-images.githubusercontent.com/7710715/45856355-b4b79e80-bd86-11e8-8bd4-626800aa4cf8.png)

![image](https://user-images.githubusercontent.com/7710715/45856382-d153d680-bd86-11e8-8358-86c368e46b45.png)

![image](https://user-images.githubusercontent.com/7710715/45856389-d9137b00-bd86-11e8-8407-ccc745fe0933.png)


Could you check if jackson databinder jar is in place?

**Comment by CheremisinVlad** [comment]
Thanks a lot. I have two jackson databinder dependecies in my project. Problem have been solved.
